version: "3.9"
services:
  db:
    image: postgres:16
    restart: always
    ports:
      - "5434:5432" # Map port 5432 inside container to 5434 on host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: webboard
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:123456@db:5432/webboard
  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

volumes:
  db_data: